### ISSUE TITLE
Node enumeration bug.

### ISSUE THREAD

**Issue by TusharRakheja** [yiboyang/graphrel#1]
After the default 0 and 1, the next node added is numbered 3, instead of 2. I believe this bug is in line 28 in graph.js.

`lastNodeId = 2,` should be `lastNodeId = 1,` I believe. (But I'm not sure about anything JavaScript, so. :P)

**Comment by yiboyang** [comment]
Indeed I forgot to update `lastNodeId` when I used a different initial configuration.

Thanks for testing!
